apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  name: controlplane-0
  labels:
    cluster.x-k8s.io/control-plane: "true"
spec:
  clusterName: $(ConfigMap.global.data.CLUSTER_NAME)
  version: $(ConfigMap.global.data.KUBERNETES_VERSION)
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: controlplane-0
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: BareMetalMachine
    name: controlplane-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: BareMetalMachine
metadata:
  name: controlplane-0
spec:
  image:
    url: "http://172.22.0.1/images/rhcos-ootpa-latest.qcow2"
    checksum: "97830b21ed272a3d854615beb54cf004"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  name: controlplane-0
spec:
  initConfiguration:
    nodeRegistration:
      name: '{{ ds.meta_data.hostname }}'
      kubeletExtraArgs:
        cloud-provider: baremetal
  clusterConfiguration:
    apiServer:
      extraArgs:
        cloud-provider: baremetal
    controllerManager:
      extraArgs:
        cloud-provider: baremetal
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  name: controlplane-1
  labels:
    cluster.x-k8s.io/control-plane: "true"
spec:
  clusterName: $(ConfigMap.global.data.CLUSTER_NAME)
  version: $(ConfigMap.global.data.KUBERNETES_VERSION)
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: controlplane-1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: BareMetalMachine
    name: controlplane-1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: BareMetalMachine
metadata:
  name: controlplane-1
spec:
  image:
    url: "http://172.22.0.1/images/rhcos-ootpa-latest.qcow2"
    checksum: "97830b21ed272a3d854615beb54cf004"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  name: controlplane-1
spec:
  joinConfiguration:
    controlPlane: {}
    nodeRegistration:
      name: '{{ ds.meta_data.hostname }}'
      kubeletExtraArgs:
        cloud-provider: baremetal
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  name: controlplane-2
  labels:
    cluster.x-k8s.io/control-plane: "true"
spec:
  clusterName: $(ConfigMap.global.data.CLUSTER_NAME)
  version: $(ConfigMap.global.data.KUBERNETES_VERSION)
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: controlplane-2
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: BareMetalMachine
    name: controlplane-2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: BareMetalMachine
metadata:
  name: controlplane-2
spec:
  image:
    url: "http://172.22.0.1/images/rhcos-ootpa-latest.qcow2"
    checksum: "97830b21ed272a3d854615beb54cf004"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  name: controlplane-2
spec:
  joinConfiguration:
    controlPlane: {}
    nodeRegistration:
      name: '{{ ds.meta_data.hostname }}'
      kubeletExtraArgs:
        cloud-provider: baremetal
