apiVersion: v1
data:
  CLUSTER_NAME: test1
  KUBERNETES_VERSION: 1.16.2
kind: ConfigMap
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: global
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: BareMetalCluster
    name: test1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: BareMetalCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1
  namespace: default
