apiVersion: v1
data:
  CLUSTER_NAME: test1
  KUBERNETES_VERSION: 1.16.2
kind: ConfigMap
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1-global
  namespace: default
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1-controlplane-0
  namespace: default
spec:
  clusterConfiguration:
    apiServer:
      extraArgs:
        cloud-provider: baremetal
    controllerManager:
      extraArgs:
        cloud-provider: baremetal
  initConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: baremetal
      name: '{{ ds.meta_data.hostname }}'
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1-controlplane-1
  namespace: default
spec:
  joinConfiguration:
    controlPlane: {}
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: baremetal
      name: '{{ ds.meta_data.hostname }}'
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1-controlplane-2
  namespace: default
spec:
  joinConfiguration:
    controlPlane: {}
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: baremetal
      name: '{{ ds.meta_data.hostname }}'
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
    cluster.x-k8s.io/control-plane: "true"
  name: test1-controlplane-0
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: test1-controlplane-0
      namespace: default
  clusterName: test1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: BareMetalMachine
    name: test1-controlplane-0
    namespace: default
  version: 1.16.2
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
    cluster.x-k8s.io/control-plane: "true"
  name: test1-controlplane-1
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: test1-controlplane-1
      namespace: default
  clusterName: test1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: BareMetalMachine
    name: test1-controlplane-1
    namespace: default
  version: 1.16.2
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
    cluster.x-k8s.io/control-plane: "true"
  name: test1-controlplane-2
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: test1-controlplane-2
      namespace: default
  clusterName: test1
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: BareMetalMachine
    name: test1-controlplane-2
    namespace: default
  version: 1.16.2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: BareMetalMachine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1-controlplane-0
  namespace: default
spec:
  image:
    checksum: 97830b21ed272a3d854615beb54cf004
    url: http://172.22.0.1/images/rhcos-ootpa-latest.qcow2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: BareMetalMachine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1-controlplane-1
  namespace: default
spec:
  image:
    checksum: 97830b21ed272a3d854615beb54cf004
    url: http://172.22.0.1/images/rhcos-ootpa-latest.qcow2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: BareMetalMachine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1-controlplane-2
  namespace: default
spec:
  image:
    checksum: 97830b21ed272a3d854615beb54cf004
    url: http://172.22.0.1/images/rhcos-ootpa-latest.qcow2
