apiVersion: v1
data:
  CLUSTER_NAME: test1
  KUBERNETES_VERSION: 1.16.2
kind: ConfigMap
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1-global
  namespace: default
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfigTemplate
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: baremetal
          name: '{{ ds.meta_data.hostname }}'
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
    nodepool: nodepool-0
  name: test1-md-0
  namespace: default
spec:
  clusterName: test1
  replicas: 2
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: test1
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: test1
        nodepool: nodepool-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
          kind: KubeadmConfigTemplate
          name: test1-md-0
          namespace: default
      clusterName: test1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: BareMetalMachineTemplate
        name: test1-md-0
        namespace: default
      version: 1.16.2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: BareMetalMachineTemplate
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1-md-0
  namespace: default
spec:
  template:
    clusterName: test1
    spec:
      image:
        checksum: 97830b21ed272a3d854615beb54cf004
        url: http://172.22.0.1/images/rhcos-ootpa-latest.qcow2
