apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: capi-quickstart
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"] # CIDR block used by Calico.
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: VSphereCluster
    name: capi-quickstart
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: VSphereCluster
metadata:
  name: capi-quickstart
spec:
  server: "$(Values.envvalues.spec.VSPHERE_SERVER)"
  cloudProviderConfiguration:
    global:
      secretName: "cloud-provider-vsphere-credentials"
      secretNamespace: "kube-system"
    virtualCenter:
      "$(Values.envvalues.spec.VSPHERE_SERVER)":
        datacenters: "$(Values.envvalues.spec.VSPHERE_DATACENTER)"
    network:
      name: "$(Values.envvalues.spec.VSPHERE_NETWORK)"
    workspace:
      server: "$(Values.envvalues.spec.VSPHERE_SERVER)"
      datacenter: "$(Values.envvalues.spec.VSPHERE_DATACENTER)"
      datastore: "$(Values.envvalues.spec.VSPHERE_DATASTORE)"
      resourcePool: "$(Values.envvalues.spec.VSPHERE_RESOURCE_POOL)"
      folder: "$(Values.envvalues.spec.VSPHERE_FOLDER)"
