---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: $(ConfigMap.global.data.CLUSTER_NAME)
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: BareMetalCluster
    name: $(ConfigMap.global.data.CLUSTER_NAME)
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: BareMetalCluster
metadata:
  name: $(ConfigMap.global.data.CLUSTER_NAME)
# spec:
#   cloudName: $(ConfigMap.global.data.CLUSTER_NAME)
#   cloudsSecret:
#     name: cloud-config
