apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  cluster.x-k8s.io/cluster-name: $(ConfigMap.global.data.CLUSTER_NAME)

resources:
- ../common/kustomizeconfig
- ../common/variables
- cluster.yaml
