apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capd-system

namePrefix: capd-

commonLabels:
    control-plane: capd-controller-manager

resources:
- provider-components.yaml
