---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../functions/compute/c01/large
- ../../../functions/network/n03
- ../../../functions/auth/aa02
- ../../../functions/storage/s02
- ../../../functions/backend/b02
