# namespace:
# - kind: Machine
#   group: cluster.x-k8s.io
#   version: v1alpha3
#   path: spec/infrastructureRef/namespace
#   create: true
# - kind: Machine
#   group: cluster.x-k8s.io
#   version: v1alpha3
#   path: spec/bootstrap/configRef/namespace
#   create: true

# commonLabels:
# - path: metadata/labels
#   create: true
#

nameReference:
- kind: KubeadmConfigTemplate
  fieldSpecs:
  - kind: MachineDeployment
    group: cluster.x-k8s.io
    path: spec/template/spec/bootstrap/configRef
- kind: BareMetalMachineTemplate
  fieldSpecs:
  - kind: MachineDeployment
    group: cluster.x-k8s.io
    path: spec/template/spec/infrastructureRef

replicas:
- path: spec/replicas
  create: true
  kind: MachineDeployment
