---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../common
- ../../global
- ../../composites/network/sriov_ovsdpdk

- ./config/endpoints.yaml
- ./config/service_accounts.yaml
